### ISSUE TITLE
Store Pattern's instead of calling Pattern.compile every time

### ISSUE THREAD

**Issue by malte0811** [InnovativeOnlineIndustries/Emojiful#11]
From a few profiling runs I did on ForgeCraft 1 [this](https://github.com/InnovativeOnlineIndustries/Emojiful/blob/61263e524199f6f115e9177d10fe4453d269f58f/src/main/java/com/hrznstudio/emojiful/render/EmojiFontRenderer.java#L101) call seems to consistently take 2-3% of the CPU time on the render thread. I'm not sure why the caching doesn't seem to be more effective, or maybe it is effective, but regex compilation is even slower than I expect.  
[This](https://github.com/InnovativeOnlineIndustries/Emojiful/blob/61263e524199f6f115e9177d10fe4453d269f58f/src/main/java/com/hrznstudio/emojiful/render/EmojiFontRenderer.java#L64) call to `String#replaceAll` might also be something to replace with a precomputed `Pattern`, something like 0.1-0.2% are going into compiling that pattern every time.

Screenshot from JMC (total number of samples: 2113):

![image](https://user-images.githubusercontent.com/10406104/98976175-55ddb200-2517-11eb-98ee-68f156a1cd54.png)

**Comment by NillerMedDild** [comment]
This issue can cause freezes when typing commands, so its impact is pretty large imo.
