### ISSUE TITLE
Custom Datapack Not Working

### ISSUE THREAD

**Issue by Coltonfr5** [InnovativeOnlineIndustries/Emojiful#113]
I'm pretty stupid when it comes to datapacks and stuff but I have the mod server and client side and I took one of the custom datapacks from the discord bot and modified each .json file to be the same as the one from the existing .json files [with name and link changes ofc] but nothing seemed to work whatsoever.
![image](https://github.com/user-attachments/assets/f9d70224-fba6-45bd-977e-89591d060e1a)
![image](https://github.com/user-attachments/assets/5cc01c9c-2a21-4ee1-8fe4-007481892fc5)

If you want the file structure then here it is
![image](https://github.com/user-attachments/assets/2ed98d96-e39b-441b-83fd-0e1b9f016c25)

I can't figure out what I'm doing wrong, I zip it up and put it in the datapacks folder and reload it and what do you know, nothing :sob:

**Comment by Buuz135** [comment]
IF you are in 1.21+ rename the recipes folder into recipe

**Comment by Coltonfr5** [comment]
I'm stupid but thanks 👍
