### ISSUE TITLE
BTTV emotes aren't animated

### ISSUE THREAD

**Issue by MelanX** [InnovativeOnlineIndustries/Emojiful#22]
Mod version: 2.1.3
Forge: 36.0.9
MC: 1.16.5

JSON:
```json
{
    "category": "Twitch_3rd_party",
    "name": "WAYTOODANK",
    "url": "https://cdn.betterttv.net/emote/5ad22a7096065b6c6bddf7f3/3x",
    "type": "emojiful:emoji_recipe"
}
```

This is an animated emote which isn't animated or even shown in MC.
Other BTTV emotes are just like PNGs, they are just not animated. Example:
```json
{
    "category": "Twitch_3rd_party",
    "name": "DonoWall",
    "url": "https://cdn.betterttv.net/emote/5efcd82551e3910deed68751/3x",
    "type": "emojiful:emoji_recipe"
}
```

**Comment by Buuz135** [comment]
Try using `https://cdn.betterttv.net/emote/5ad22a7096065b6c6bddf7f3/3x.gif` with the file extension

**Comment by MelanX** [comment]
It works. If you don't plan to fix that you don't need the extension, you could close it :)

**Comment by Buuz135** [comment]
It needs the extension as reference.
