### ISSUE TITLE
Chat emojis output wrong

### ISSUE THREAD

**Issue by YOYOK9** [InnovativeOnlineIndustries/Emojiful#26]
Not sure if this is a bug, or really what to call it, But it looks like the chat output is off, Basically it shows the emoji but right after it shows the text of what the emoji is. 
EX: :) in chat outputs
![image](https://user-images.githubusercontent.com/12290062/110420746-f37e6380-8069-11eb-935a-2796ef189660.png)
All other emojis do the same. 
![image](https://user-images.githubusercontent.com/12290062/110420912-6982ca80-806a-11eb-961e-cb8ea151b826.png)

MC: 1.16.5
Forge: 36.0.46
Emojifull: 1.16.4-2.1.4

**Comment by BlackJamesYT** [comment]
Same for me :o

**Comment by phit** [comment]
still an issue on 1.18 with 3.0.1

**Comment by GrigLog** [comment]
This happens on servers with changed chat formatting. Instead of "< Player > Message" chat looks like "Player: Message". Since ":" is a special symbol in Emojiful, parsing goes wrong.
Solution is very simple: add a config for specifying the Emojiful symbol. Or at least make one static field `char SPECIAL = ':'` to make it easier for others to edit. 
I myself has replaced ":" with "!" for my server and it works fine.

**Comment by purejosh** [comment]
@Buuz135 This has been present for over a year and a half. Not a single comment on this Github. What's the status of fixing this bug? It essentially renders your mod useless.

**Comment by codeHusky** [comment]
Should be fixed in my PR - waiting on a merge and then should be resolved. Sucks that it took this long for it to get fixed but, yeah.

**Comment by purejosh** [comment]
Very cool!

**Comment by Axelouuu-dev** [comment]
Nice !

**Comment by Landor151** [comment]
> still an issue on 1.18 with 3.0.1

Have you found a solution yet?

**Comment by purejosh** [comment]
> > still an issue on 1.18 with 3.0.1
> 
> Have you found a solution yet?

Update?

**Comment by V972** [comment]
> > > still an issue on 1.18 with 3.0.1
> > 
> > 
> > Have you found a solution yet?
> 
> Update?

Judging from other issues, the dev doesn't update/fix non-latest-ish versions.
Maybe if someone submits a PR on 1.18? Idk.
