### ISSUE TITLE
NPE Crash in EmojiFontRenderer

### ISSUE THREAD

**Issue by viceversagames** [InnovativeOnlineIndustries/Emojiful#31]
https://github.com/InnovativeOnlineIndustries/Emojiful/issues/17 did not seem to resolve this crash.

https://pastebin.com/SSUS4En8

**Comment by NielsPilgaard** [comment]
Seems like this is still a thing :/
https://gist.github.com/NillerMedDild/1c201a4fcd097bb43d362db858abd7cd
