### ISSUE TITLE
1.12 Support

### ISSUE THREAD

**Issue by cmod31** [InnovativeOnlineIndustries/Emojiful#32]
Hey most mods are still in 1.12 so are the modpacks.
The 1.12 version is nothing like the newest version, would be cool if it still got updates.
Also great mod thanks

**Comment by Buuz135** [comment]
No

**Comment by cmod31** [comment]
why not can you take a bit time to answer please

**Comment by Buuz135** [comment]
I dont want to support 50 versions

**Comment by cmod31** [comment]
Its just the most used version for modding at the time but ok its your mod. no problem :)

**Comment by Buuz135** [comment]
That is your opinion and not a fact

**Comment by cmod31** [comment]
I don't want to argue here so my last message is the 1.16 has much less mods than 1.12 and thats a fact but do what you want its not my mod its fine

**Comment by Buuz135** [comment]
![firefox_CiLYDWfSPF](https://user-images.githubusercontent.com/3874674/141966843-8774f889-2327-46ef-abf1-e608519a15bc.png)
![firefox_A0vT5A68Av](https://user-images.githubusercontent.com/3874674/141966912-6659bf84-63c5-474f-a0bf-3de9f9bd1939.png)

**Comment by MicroNeutron** [comment]
I dont know what limit you added but in my cf lagacy  1.12.2 got 1096 pages but even whole 1.16 got only 744. Making fake data on purpose is immoral.
