### ISSUE TITLE
1.18 Soap chat and interface

### ISSUE THREAD

**Issue by sssHpion007** [InnovativeOnlineIndustries/Emojiful#34]
It happened that even health and hunger became soapy.
https://youtu.be/QBaFiuFgaMI

**Comment by moon-st0ne** [comment]
confirmed on latest version of emojiful 1.18

**Comment by Tokerot** [comment]
i'm currently using the 1.18 mod version in 1.18.1 minecraft works fine other than the "soapy" blurry text and hud elements that randomly blur and unblur

**Comment by Buuz135** [comment]
Does it happen with just the mod alone? What mods were you using? Where you using optifine?

**Comment by Tokerot** [comment]
just tested, works fine by itself, but gets "soapy"/blurry with optifines current release OptiFine HD U H4. causes head elements such as hunger and hearts to be blurry as well as text and the game menu. the blur sometimes clears, but is blurry most of the time. gui screens like inventory, crafting tables/etc are fine other than text, items are fine. turning custom fonts on and off clears screen but will go blurry again on either. turning on antriscopic filtering (any amount) fixes the health/hunger blur but text blurs remains regardless of any settings changes, thats all i can think of testing wise, but seems it is a clash between emojiful and optifine

launching again hunger and health is blurry again even tho antriscopic filtering is still on, changing the setting again will fix health/hunger but only temporarily
just found there is no blur on text or hunger/health (seemingly permanently) if you change gui scale to 1, but blurs on 2/3/4/auto unfortunately gui scale 1 is teeny tiny on my large monitor

**Comment by Buuz135** [comment]
Should be fixed in 1.19
