### ISSUE TITLE
[Request] Fabric Version

### ISSUE THREAD

**Issue by iCaitlyn** [InnovativeOnlineIndustries/Emojiful#38]
Are there any plans to develop a Fabric version?

**Comment by vaporvee** [comment]
I'm also interested in a fabric version

But if no one knows how to do that then maybe a "help wanted" label is needed

**Comment by iCaitlyn** [comment]
There seems to have been an attempt at https://github.com/InnovativeOnlineIndustries/Emojiful-Fabric

But it otherwise seems like the progress on it has stalled?

**Comment by EGOIST1372** [comment]
@Buuz135 I know you busy but can we get an/a update/news on this issue?
