### ISSUE TITLE
Update 1.12.2 to 2.0v?

### ISSUE THREAD

**Issue by PixelmonPRO** [InnovativeOnlineIndustries/Emojiful#4]
Good day! I know that Minecraft is not standing still and it is already necessary to switch to 1.16.+ versions, but many servers are still working on version 1.12.2, due to the fact that updates to the server core, other mods, plugins have not yet been updated...
Therefore, I ask you to add support for animated emoji to 1.12.2, and possibly a list of emoji, if possible.
Thank you for this wonderful mod :)

**Comment by Buuz135** [comment]
Nope
