### ISSUE TITLE
Weird Texture Bug

### ISSUE THREAD

**Issue by ftk789** [InnovativeOnlineIndustries/Emojiful#44]
Downloaded the datapack from your server and bot, Then This came up :
 
![image](https://user-images.githubusercontent.com/57598907/175805912-a925eaab-0bc1-4f18-91b0-b34b02f8d671.png)
You see that weird glitch? Even some emotes are glitchy

**Comment by ftk789** [comment]
Also is there a way to make the emotes bigger in chat? Maybe an emote size control

**Comment by ftk789** [comment]
![image](https://user-images.githubusercontent.com/57598907/175806032-db321c39-bd64-46bf-a69b-6c8d6dd5c545.png)

**Comment by Buuz135** [comment]
Are you using optifine?

**Comment by ftk789** [comment]
Yes I am using optifine as a mod in Forge 1.18.1 and a texture pack as well

**Comment by Buuz135** [comment]
Then don't use optifine, it breaks everything

**Comment by ftk789** [comment]
It turns out it's not optifine, It's a recourse pack I was using, You should've not closed the issue since it should be fixed kindly by the mod creators of course etc...
