### ISSUE TITLE
Mod breaks Discord Integration In-Game chat messages from displaying correctly

### ISSUE THREAD

**Issue by ApexModder** [InnovativeOnlineIndustries/Emojiful#47]
Minecraft Version: 1.19.2
Forge Version: 43.1.27
Mod Version: 1.19-3.1.3

If this mod is installed along side [DiscordIntegration](https://www.curseforge.com/minecraft/mc-mods/dcintegration) the in-game messages which are synced from Discord fail to display the message content.

Removing this mod allows DiscordIntegrations messages to display in chat fine.

Releated [Discord-Integration Issue](https://github.com/ErdbeerbaerLP/DiscordIntegration-Forge/issues/489)

**Comment by Avakining** [comment]
Also applies to Emojiful 4.0.3 for Fabric and  DiscordIntegration 2.5.0 for Fabric 1.19.2 (0.14.11)

**Comment by Maethorel** [comment]
Still seeing this issue.

Minecraft 1.19.2
Forge 43.2.3
Emojiful 4.1.0
(Discord Integration is version 2.6.2)
