### ISSUE TITLE
breaks baritone chat for some reason

### ISSUE THREAD

**Issue by machineonamission** [InnovativeOnlineIndustries/Emojiful#65]
normal behavior:
![image](https://user-images.githubusercontent.com/35177464/207490124-6bd558d0-0376-4958-8720-216ce9d7d122.png)
![image](https://user-images.githubusercontent.com/35177464/207490143-2e0f7277-610e-4ca6-9e92-d41e24f70454.png)

with emojiful:
![image](https://user-images.githubusercontent.com/35177464/207490339-79a750b1-3555-4757-8dc7-3cb1edbec3c6.png)
![image](https://user-images.githubusercontent.com/35177464/207490374-fec1230c-9894-4e00-92c6-119262b54a30.png)

**Comment by Buuz135** [comment]
Should be fixed in 4.0.5
