### ISSUE TITLE
Upload on Modrinth Please

### ISSUE THREAD

**Issue by sternschnaube** [InnovativeOnlineIndustries/Emojiful#67]
https://modrinth.com/

**Comment by Rafii2198** [comment]
I wanted to make a modpack on Modrinth, and as Cursforge made it, so their mods are forbidden on Modrinth's packs, I can't include this mod which would really like! I could attach it as an external file, but that way the author would not earn any money, and I feel that would be unfair. Having it on Modrinth would solve this.

**Comment by Felix14-v2** [comment]
>  their mods are forbidden on Modrinth's packs

To be more precise, CurseForge itself prohibits the use of its resources everywhere outside of CurseForge.

**Comment by sternschnaube** [comment]
I know a lot of mods with the presence on Curse and Modrinth. Personal, I see no problem at this - but if some mods having different licenses, it's may a different topic.

I was not digging into the rules of Curse - but I see that just more from the protective way.
Reuploads are forbidden - it exist too many (trash) sites - the user is in the end not protected anymore.

Modrinth is a different case 😊

**Comment by Felix14-v2** [comment]
> Reuploads are forbidden - it exist too many (trash) sites - the user is in the end not protected anymore.
> 
> Modrinth is a different case 😊

A bit offtopic, but CurseForge deliberately forbade Modrinth to use links to its mods in modpacks:
https://blog.modrinth.com/p/modpack-changes

**Comment by sternschnaube** [comment]
It makes sense from the view of Curse.
(If they see their dominating role in danger, the steps coming fast - wish I could say the same about announced site features after over 2+ years.)

Personal - I don't care about mod packs, since I always create my own one. Having the mod(s) on Modrinth gives it access to a bigger audience 🥳
And it's great for Modrinths own mod pack-ecosystem - like @Rafii2198 was mentioning already. 

Modrinth is currently the best Minecraft resource site - Curse is sleeping too much. But every site has ups and downs. (And Curse makes really nothing to get into competition against Modrinth, yet.)

But enough off topic, I love this mod and that's why I was recommending Modrinth 👍🏿

**Comment by Rafii2198** [comment]
Also, one thing we should add is that `mc-publish` already used to publish the mod to CurseForge, supports Modrinth too, meaning little few changes would be needed to automatically support Modrinth!

**Comment by Buuz135** [comment]
Done

**Comment by sternschnaube** [comment]
Thank you @Buuz135 ☺️
