### ISSUE TITLE
Chat displaying issue with some formatting

### ISSUE THREAD

**Issue by Scarlaid** [InnovativeOnlineIndustries/Emojiful#68]
So I was just doing the inspection today (CoreProtect), I realized most of the logs disappeared
Doubt myself having many QoL mods, I removed the most recent ones, including Emojiful, the log displayed normally, adding back one-one, I found out Emojiful causing such issue
I do also use other mods that involve in chat modification, like [RestoreChatLink](https://github.com/zomabies/RestoreChatLinks) and [Where's My Chat History](https://github.com/mrbuilder1961/WheresMyChatHistory), but having both have no issue at all until Emojiful was installed

The log with Emojiful: [latest.log](https://github.com/InnovativeOnlineIndustries/Emojiful/files/10422378/latest.log)
The log without Emojiful: [2023-01-16-3.log](https://github.com/InnovativeOnlineIndustries/Emojiful/files/10422380/2023-01-16-3.log)
My mod list: [installed-mods.txt](https://github.com/InnovativeOnlineIndustries/Emojiful/files/10422384/installed-mods.txt)

Without Emojiful 
![javaw_Th6ht9ORyU](https://user-images.githubusercontent.com/90851437/212594737-931b54e5-34e9-4487-a8c3-a55545c67db9.png)

With Emojiful
![image](https://user-images.githubusercontent.com/90851437/212594934-0cb7834d-6b77-4c63-8d3c-d609255b057c.png)

**Comment by NielsPilgaard** [comment]
The same thing happens with Spark in Enigmatica 9: https://github.com/EnigmaticaModpacks/Enigmatica9/issues/625

**Comment by NielsPilgaard** [comment]
@Buuz135 We'd appreciate if you could look into this, breaking chat output from mods can be quite annoying, especially when it comes to servers with customized chats.
