### ISSUE TITLE
crushes when sending emojis

### ISSUE THREAD

**Issue by empty7878** [InnovativeOnlineIndustries/Emojiful#71]
https://user-images.githubusercontent.com/125138961/218263760-6713dcba-f793-4a4e-88a2-1ffc97a097fa.mp4

**Comment by Witixin1512** [comment]
Which version of Minecraft, Emojiful is this on?
Also, which loader?

**Comment by empty7878** [comment]
> Which version of Minecraft, Emojiful is this on? Also, which loader?

version 1.19.2 Forge, emojuful on, loader - tlauncher (pirate)

**Comment by Buuz135** [comment]
Modified client, no support
