### ISSUE TITLE
The mod shows warning emojis instead of custom animated ones

### ISSUE THREAD

**Issue by f1refa11** [InnovativeOnlineIndustries/Emojiful#72]
![javaw_Uj0jVRdzuv](https://user-images.githubusercontent.com/58619409/218836489-18aca989-70cb-4985-a8b5-4d1a5b3691d4.png) instead of :bongocat:
The non-animated emojis are working, but they are in low quality:
![изображение](https://user-images.githubusercontent.com/58619409/218838126-1341ac53-ef6d-4694-8481-05cb49b5c898.png)
![изображение](https://user-images.githubusercontent.com/58619409/218838743-6d190744-4319-43ee-bf92-520f86e3be04.png)
All used mods:
![explorer_MLzKQI6LIX](https://user-images.githubusercontent.com/58619409/218836744-4e3f92fc-fca3-4ad9-a5b0-af3bb96f8ad8.png)
![explorer_EHonmp0Q64](https://user-images.githubusercontent.com/58619409/218836807-20cdcc61-7dbc-425b-b340-356e33aaafdb.png)
Are there any mods from the mods list that can cause this issue?

**Comment by f1refa11** [comment]
Update:
After some reconnects, the animated emojis are showing, but only the first frame and, of course, they are low-quality.
![изображение](https://user-images.githubusercontent.com/58619409/218929400-0715d806-b174-41f6-9679-247ad175da7f.png)

**Comment by bluebear94** [comment]
Try disabling Exordium’s sign buffering feature.

**Comment by f1refa11** [comment]
Yeah, it resolved the issue, thanks!
