### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "net.minecraftforge.common.ForgeConfigSpec$BooleanValue.get()" because "com.hrznstudio.emojiful.platform.ForgeConfigHelper.loadCustom" is null

### ISSUE THREAD

**Issue by aaronhowser1** [InnovativeOnlineIndustries/Emojiful#73]
https://gist.github.com/aacac009bb3c461217bb9076ec7c1d37

I have no idea why this happens. It happens sometimes and only sometimes. When it breaks, I disable the mod and try again in a couple days and it works.

**Comment by Buuz135** [comment]
This happens when another mod crashes and forge blames Emojiful, if you remove Emojiful it will tell you the mod that is causing issues.
