### ISSUE TITLE
Emojiful breaks Patchouli book text rendering

### ISSUE THREAD

**Issue by Ellpeck** [InnovativeOnlineIndustries/Emojiful#8]
If Emojiful is added to any modpack that contains Patchouli (and a mod that adds a patchouli book), this issue arises:
![image](https://user-images.githubusercontent.com/5741138/96001560-73e0c580-0e38-11eb-83b3-17ce4ad48e3a.png)

It looks like what is happening is that Patchouli's $(tags) that can be used for formatting get included as part of the width calculation somehow, causing big gaps to appear before and after formatted words.

Minecraft 1.16.3
Forge 34.1.19
Patchouli 44
Emojiful 2.1.0

Tested with just Patchouli, Nature's Aura and Emojiful as well as just Patchouli, Ars Noveau (and its dependencies) and Emojiful.

**Comment by Buuz135** [comment]
https://github.com/InnovativeOnlineIndustries/Emojiful/commit/448100f2709b88ac65da18d73ad50a75a070bcc4
