### ISSUE TITLE
[bug] 1.19.2 mod incompatibility with Emojiful after supplementaries-1.19.2-2.3.10

### ISSUE THREAD

**Issue by CKY-** [InnovativeOnlineIndustries/Emojiful#80]
- A log if the issue is casing a crash. These are found in your instance directory under /logs
[https://gist.github.com/CKY-/14a7fd169dc27d10be87e7fce22b05e6](https://gist.github.com/CKY-/14a7fd169dc27d10be87e7fce22b05e6)
- Mod version, MC version and Loader you are using
CurseForge 
1.19.2
- A description of your issue and how to reproduce
This is a mod incompatibility with Emojiful-Forge-1.19.2-4.0.4 or Emojiful-Forge-1.19.2-4.0.3
installing 
supplementaries-1.19.2-2.3.14
supplementaries-1.19.2-2.3.14a
supplementaries-1.19.2-2.3.17
all result in the same crash
[https://github.com/MehVahdJukaar/Supplementaries/issues/643](https://github.com/MehVahdJukaar/Supplementaries/issues/643
)

**Comment by MR-Spagetty** [comment]
Your issue may actually be due to the forge version, i had a similar crash without supplementeries on forge 1.19.2 43.2.0 and switching to forge 43.2.3 fixed it

**Comment by Buuz135** [comment]
Thats a config issue, you need to delete the emojiful config file, or the mod is wrongfuly getting blamed by another mods crash
