### ISSUE TITLE
1.19.4 support

### ISSUE THREAD

**Issue by MegaSa1nt** [InnovativeOnlineIndustries/Emojiful#82]
Will it update to 1.19.4? It would be awesome!

**Comment by MegaSa1nt** [comment]
About 1.20.1: it sadly doesn't work for me
![image](https://github.com/InnovativeOnlineIndustries/Emojiful/assets/49565695/50f90bd8-4129-4565-91d3-c2d5ba495f8f)
![image](https://github.com/InnovativeOnlineIndustries/Emojiful/assets/49565695/08b1e5eb-dc3e-4eca-8b55-a81c1dfdc092)

**Comment by Buuz135** [comment]
Thats a bad minecraft installation, also 1.19.4 nah
