### ISSUE TITLE
[Request] Integration with Diskordel

### ISSUE THREAD

**Issue by vico93** [InnovativeOnlineIndustries/Emojiful#93]
Don't know if integrations with Discord relay mods need to be coded case-by-case, anyway would be amazing if @Jagenka's [Diskordel](https://github.com/Jagenka/DisKordel) ([MR](https://modrinth.com/mod/diskordel)) could be supported by Emojiful.

Relevant issue on Diskordel's side: [#160](https://github.com/Jagenka/DisKordel/issues/160)

**Comment by Jagenka** [comment]
should only be a request on my side, as Emojiful only renders text differently (please correct me if I'm wrong)

**Comment by Buuz135** [comment]
Yeah, it's just a font renderer. If you can send the Discord emojis to the game as :emoji: in lower case the mod will just catch it just fine

**Comment by vico93** [comment]
My Bad. I though support would need to be added in both sides due to custom emoji's stuff.
